//! Backend contracts for gix-backed reads and explicit Git operations.
//!
//! Implementations intentionally arrive in later milestones. These traits keep
//! backend lifetimes and gix types inside this crate while exposing only owned
//! `sourcefour-model` values.

mod discover;

use std::sync::atomic::AtomicBool;

pub use crate::discover::{discover, display_name};

use sourcefour_model::{
    CommitDetail, CommitFiles, CreateBranchRequest, FetchRequest, FileDiff, FileDiffRequest,
    HistoryBatch, HistoryQuery, OperationOutcome, OperationProgress, RepoFailure, RepoSnapshot,
    WorktreeId,
};

/// Read-only repository access implemented with gix in later milestones.
pub trait RepoReader: Send + Sync {
    /// Obtains the repository metadata snapshot for an active worktree context.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when repository metadata cannot be read.
    fn snapshot(&self, active_worktree: Option<&WorktreeId>) -> Result<RepoSnapshot, RepoFailure>;

    /// Starts a persistent, incrementally consumed history traversal.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when the requested roots cannot be resolved.
    fn start_history(&self, query: HistoryQuery) -> Result<Box<dyn HistoryCursor>, RepoFailure>;

    /// Reads metadata for one selected commit.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when the object cannot be decoded.
    fn commit_detail(&self, oid: sourcefour_model::Oid) -> Result<CommitDetail, RepoFailure>;

    /// Reads changed-file summaries for one commit/parent comparison.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when the trees cannot be compared.
    fn commit_files(
        &self,
        oid: sourcefour_model::Oid,
        parent: sourcefour_model::DiffParent,
    ) -> Result<CommitFiles, RepoFailure>;

    /// Reads one bounded file diff.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when the request cannot be completed.
    fn file_diff(&self, request: FileDiffRequest) -> Result<FileDiff, RepoFailure>;
}

/// Long-lived, single-consumer history traversal.
pub trait HistoryCursor: Send {
    /// Produces at most `max_rows` matching rows unless cancellation is observed.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when traversal cannot continue.
    fn next_batch(
        &mut self,
        max_rows: usize,
        cancelled: &AtomicBool,
    ) -> Result<HistoryBatch, RepoFailure>;
}

/// Explicit user-initiated Git operations.
pub trait RepoOperator: Send + Sync {
    /// Fetches according to an explicit argv-safe request.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when Git cannot start or complete the operation.
    fn fetch(
        &self,
        request: FetchRequest,
        sink: &dyn OperationSink,
        cancelled: &AtomicBool,
    ) -> Result<OperationOutcome, RepoFailure>;

    /// Creates a branch, optionally checking it out.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when Git cannot start or complete the operation.
    fn create_branch(
        &self,
        request: CreateBranchRequest,
        sink: &dyn OperationSink,
        cancelled: &AtomicBool,
    ) -> Result<OperationOutcome, RepoFailure>;
}

/// Receives rate-limited progress generated by an operation runner.
pub trait OperationSink: Send + Sync {
    /// Accepts one progress update.
    fn report(&self, progress: OperationProgress);
}

/// Watches metadata-only repository changes without recursively watching files.
pub trait MetadataWatcher: Send {
    /// Returns one coalesced change notice when available.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when watcher state cannot be read.
    fn poll(&mut self) -> Result<Option<MetadataChange>, RepoFailure>;
}

/// Metadata change reported by a watcher implementation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MetadataChange {
    /// Reference names or targets changed.
    Refs,
    /// Worktree registration or metadata changed.
    Worktrees,
    /// Both metadata groups changed during a debounce interval.
    RefsAndWorktrees,
}

/// Marker proving this crate is linked to the pinned gix dependency.
///
/// The marker avoids exposing any gix values in public backend contracts.
#[must_use]
pub const fn pinned_gix_version() -> &'static str {
    let _ = core::marker::PhantomData::<gix::Repository>;
    "0.85"
}

#[cfg(test)]
mod tests {
    use super::pinned_gix_version;

    #[test]
    fn publishes_the_tested_minor_version() {
        assert_eq!(pinned_gix_version(), "0.85");
    }
}
