//! Backend contracts for gix-backed reads and explicit Git operations.
//!
//! Implementations intentionally arrive in later milestones. These traits keep
//! backend lifetimes and gix types inside this crate while exposing only owned
//! `sourcefour-model` values.

mod ahead_behind;
mod detail;
mod diff;
mod discover;
mod fetch;
mod files;
mod history;
mod refs;
mod session;
mod watch;
mod worktrees;

use std::sync::atomic::AtomicBool;

pub use crate::{
    ahead_behind::{AheadBehindCache, apply as apply_ahead_behind},
    detail::commit_detail,
    diff::{DiffLimits, file_diff, file_diff_with_limits},
    discover::{discover, display_name},
    fetch::fetch,
    files::commit_files,
    history::{FIRST_BATCH_ROWS, GixHistoryCursor, NEXT_BATCH_ROWS},
    refs::{References, references},
    session::snapshot,
    watch::{MetadataChange, MetadataWatcher},
    worktrees::worktrees,
};

use sourcefour_model::{
    CommitDetail, CommitFiles, CreateBranchRequest, FetchRequest, FileDiff, FileDiffRequest,
    HistoryBatch, HistoryQuery, OperationOutcome, OperationProgress, RepoFailure, RepoSnapshot,
    WorktreeId,
};

/// Read-only repository access implemented with gix in later milestones.
pub trait RepoReader: Send + Sync {
    /// Obtains the repository metadata snapshot for an active worktree context.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when repository metadata cannot be read.
    fn snapshot(&self, active_worktree: Option<&WorktreeId>) -> Result<RepoSnapshot, RepoFailure>;

    /// Starts a persistent, incrementally consumed history traversal.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when the requested roots cannot be resolved.
    fn start_history(&self, query: HistoryQuery) -> Result<Box<dyn HistoryCursor>, RepoFailure>;

    /// Reads metadata for one selected commit.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when the object cannot be decoded.
    fn commit_detail(&self, oid: sourcefour_model::Oid) -> Result<CommitDetail, RepoFailure>;

    /// Reads changed-file summaries for one commit/parent comparison.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when the trees cannot be compared.
    fn commit_files(
        &self,
        oid: sourcefour_model::Oid,
        parent: sourcefour_model::DiffParent,
    ) -> Result<CommitFiles, RepoFailure>;

    /// Reads one bounded file diff.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when the request cannot be completed.
    fn file_diff(&self, request: FileDiffRequest) -> Result<FileDiff, RepoFailure>;
}

/// Long-lived, single-consumer history traversal.
///
/// §6.9 sketches `next_batch(max_rows, &AtomicBool)`, but the traversal owns its
/// repository on a worker thread (§6.3) and therefore owns its cancellation flag
/// too; a borrowed flag cannot outlive the call while the thread still needs it.
/// Cancellation is a separate method instead.
pub trait HistoryCursor: Send {
    /// Produces at most `max_rows` matching rows, resuming the traversal.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when traversal cannot continue.
    fn next_batch(&mut self, max_rows: usize) -> Result<HistoryBatch, RepoFailure>;

    /// Stops the traversal at the next row boundary.
    fn cancel(&self);
}

/// Explicit user-initiated Git operations.
pub trait RepoOperator: Send + Sync {
    /// Fetches according to an explicit argv-safe request.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when Git cannot start or complete the operation.
    fn fetch(
        &self,
        request: FetchRequest,
        sink: &dyn OperationSink,
        cancelled: &AtomicBool,
    ) -> Result<OperationOutcome, RepoFailure>;

    /// Creates a branch, optionally checking it out.
    ///
    /// # Errors
    ///
    /// Returns a typed failure when Git cannot start or complete the operation.
    fn create_branch(
        &self,
        request: CreateBranchRequest,
        sink: &dyn OperationSink,
        cancelled: &AtomicBool,
    ) -> Result<OperationOutcome, RepoFailure>;
}

/// Receives rate-limited progress generated by an operation runner.
pub trait OperationSink: Send + Sync {
    /// Accepts one progress update.
    fn report(&self, progress: OperationProgress);
}

/// Marker proving this crate is linked to the pinned gix dependency.
///
/// The marker avoids exposing any gix values in public backend contracts.
#[must_use]
pub const fn pinned_gix_version() -> &'static str {
    let _ = core::marker::PhantomData::<gix::Repository>;
    "0.85"
}

#[cfg(test)]
mod tests {
    use super::pinned_gix_version;

    #[test]
    fn publishes_the_tested_minor_version() {
        assert_eq!(pinned_gix_version(), "0.85");
    }
}
