[package]
name = "sourcefour-doc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
encoding_rs.workspace = true
pulldown-cmark.workspace = true
rtf-grimoire.workspace = true
thiserror.workspace = true

[lints]
workspace = true
