[package]
name = "sourcefour-git"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
gix.workspace = true
smallvec.workspace = true
sourcefour-model = { path = "../sourcefour-model" }

[dev-dependencies]
sourcefour-test-support = { path = "../sourcefour-test-support" }

[lints]
workspace = true
