[package]
name = "sourcefour-graph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
smallvec.workspace = true
sourcefour-model = { path = "../sourcefour-model" }

[lints]
workspace = true
